### ISSUE TITLE
Yum cache is not empty in the openstack-full role

### ISSUE THREAD

**Issue by lebauce** [enovance/edeploy-roles#132]
/var/cache/yum contains 2 folders "InstallMedia" and "x86_64" that use 167 of disk space

**Comment by EmilienM** [comment]
I think you may want to patch edeploy-roles to purge this directory at each build, isn't ?

**Comment by ErwanAliasr1** [comment]
I mean https://github.com/enovance/edeploy-roles/blob/master/openstack-full.install#L519 is supposed to clean that but obviously we still have a lot of disk space used for nothing.

So the cleaning doesn't seems to work very well.

**Comment by lebauce** [comment]
Here is the list of the packages

/var/cache/yum/InstallMedia/packages
/var/cache/yum/InstallMedia/packages/glibc-common-2.17-55.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libgcc-4.8.2-16.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libverto-0.2.5-4.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libffi-3.0.13-11.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libmount-2.23.2-16.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/pam-1.1.8-9.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/elfutils-libelf-0.158-3.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libutempter-1.1.6-4.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/audit-libs-2.3.3-4.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libsepol-2.1.9-3.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/cyrus-sasl-lib-2.1.26-17.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/gzip-1.5-7.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/python-libs-2.7.5-16.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/glib2-2.36.3-5.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/curl-7.29.0-19.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libuser-0.60-5.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/rpm-build-libs-4.11.1-16.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/setup-2.8.71-4.el7.noarch.rpm
/var/cache/yum/InstallMedia/packages/systemd-libs-208-11.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libdb-5.3.21-17.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/shadow-utils-4.1.5.1-13.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/ncurses-base-5.9-13.20130511.el7.noarch.rpm
/var/cache/yum/InstallMedia/packages/python-iniparse-0.4-9.el7.noarch.rpm
/var/cache/yum/InstallMedia/packages/info-5.1-4.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/nss-util-3.15.4-2.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/glibc-2.17-55.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/ncurses-libs-5.9-13.20130511.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/pcre-8.32-12.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/cracklib-dicts-2.9.0-11.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/ca-certificates-2013.1.95-71.el7.noarch.rpm
/var/cache/yum/InstallMedia/packages/nss-softokn-freebl-3.15.4-2.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libpwquality-1.2.3-4.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libuuid-2.23.2-16.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/bash-4.2.45-5.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libstdc++-4.8.2-16.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/p11-kit-0.18.7-4.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libsemanage-2.1.10-16.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/p11-kit-trust-0.18.7-4.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libselinux-2.2.2-6.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libcap-ng-0.7.3-5.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libcurl-7.29.0-19.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/python-2.7.5-16.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libxml2-2.9.1-5.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libcap-2.22-8.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/openssl-libs-1.0.1e-34.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libassuan-2.1.0-3.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libacl-2.2.51-12.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/pyxattr-0.5.1-5.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/nspr-4.10.2-4.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/file-libs-5.11-21.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libgpg-error-1.12-3.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/pygpgme-0.3-9.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libblkid-2.23.2-16.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/lua-5.1.4-14.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/pinentry-0.8.1-14.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/popt-1.13-16.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/sqlite-3.7.17-4.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/pth-2.0.7-22.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/nss-softokn-3.15.4-2.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/pkgconfig-0.27.1-4.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/openldap-2.4.39-3.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/nss-sysinit-3.15.4-6.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/basesystem-10.0-7.el7.noarch.rpm
/var/cache/yum/InstallMedia/packages/grep-2.16-1.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/coreutils-8.22-11.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/rpm-python-4.11.1-16.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/krb5-libs-1.11.3-49.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libattr-2.4.46-12.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/expat-2.1.0-8.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libtasn1-3.3-3.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/ncurses-5.9-13.20130511.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/nss-tools-3.15.4-6.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/rpm-4.11.1-16.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/zlib-1.2.7-13.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/gnupg2-2.0.22-3.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/dbus-libs-1.6.12-8.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/gpgme-1.3.2-5.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/keyutils-libs-1.5.8-3.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/shared-mime-info-1.1-7.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libidn-1.28-3.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/python-pycurl-7.19.0-17.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/ustr-1.0.4-16.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/yum-metadata-parser-1.1.4-10.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libssh2-1.4.3-8.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/gmp-5.1.1-5.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libgcrypt-1.5.3-4.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/filesystem-3.2-18.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/gawk-4.0.2-4.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/pyliblzma-0.5.3-11.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/util-linux-2.23.2-16.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/xz-libs-5.1.2-8alpha.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/nss-3.15.4-6.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/libdb-utils-5.3.21-17.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/cracklib-2.9.0-11.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/bzip2-libs-1.0.6-12.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/rpm-libs-4.11.1-16.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/sed-4.2.2-5.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/cpio-2.11-22.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/yum-3.4.3-118.el7.noarch.rpm
/var/cache/yum/InstallMedia/packages/libcom_err-1.42.9-4.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/diffutils-3.3-4.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/readline-6.2-9.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/gdbm-1.10-8.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/chkconfig-1.3.61-4.el7.x86_64.rpm
/var/cache/yum/InstallMedia/packages/tzdata-2014b-1.el7.noarch.rpm
/var/cache/yum/InstallMedia/packages/python-urlgrabber-3.10-4.el7.noarch.rpm

**Comment by ErwanAliasr1** [comment]
Sounds like a base issue not openstack-full....

**Comment by EmilienM** [comment]
@ErwanAliasr1 +1

**Comment by ErwanAliasr1** [comment]
I'll have a look on that.

**Comment by ErwanAliasr1** [comment]
Solved by https://github.com/enovance/edeploy/commit/28db1973859fb3cda4d9c141ae289f033e55b797
